USE BikeStores
GO

CREATE TABLE Products (
	ProductID INT IDENTITY (1, 1) PRIMARY KEY,
	ProductName VARCHAR (255) NOT NULL,
	BrandID INT NOT NULL,
	CategoryID INT NOT NULL,
	ModelYear SMALLINT NOT NULL,
	ListPrice DECIMAL (10, 2) NOT NULL,
	FOREIGN KEY (CategoryID) REFERENCES Categories (CategoryID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (BrandID) REFERENCES Brands (BrandID) ON DELETE CASCADE ON UPDATE CASCADE
);