USE BikeStores
GO

CREATE TABLE Staffs (
	StaffID INT IDENTITY (1, 1) PRIMARY KEY,
	FirstName VARCHAR (50) NOT NULL,
	LastName VARCHAR (50) NOT NULL,
	Email VARCHAR (255) NOT NULL UNIQUE,
	Phone VARCHAR (25),
	Active tinyint NOT NULL,
	StoreID INT NOT NULL,
	ManagerID INT,
	FOREIGN KEY (StoreID) REFERENCES Stores (StoreID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (ManagerID) REFERENCES Staffs (StaffID) ON DELETE NO ACTION ON UPDATE NO ACTION
);