USE BikeStores
GO

CREATE TABLE OrderItems (
	OrderID INT,
	ItemID INT,
	ProductID INT NOT NULL,
	Quantity INT NOT NULL,
	ListPrice DECIMAL (10, 2) NOT NULL,
	Discount DECIMAL (4, 2) NOT NULL DEFAULT 0,
	PRIMARY KEY (OrderID, ItemID),
	FOREIGN KEY (OrderID) REFERENCES Orders (OrderID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (ProductID) REFERENCES Products (ProductID) ON DELETE CASCADE ON UPDATE CASCADE
);