USE BikeStores
GO

CREATE TABLE Stocks (
	StoreID INT,
	ProductID INT,
	Quantity INT,
	PRIMARY KEY (StoreID, ProductID),
	FOREIGN KEY (StoreID) REFERENCES Stores (StoreID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (ProductID) REFERENCES Products (ProductID) ON DELETE CASCADE ON UPDATE CASCADE
);